<a href="https://colab.research.google.com/github/alexgelde/IA/blob/main/lab2IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


rows = 5

for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
# Get the input from the user
number = int(input("Enter a number: "))

# Initialize the sum
sum_of_numbers = 0

# Calculate the sum of numbers from 1 to the given number
for i in range(1, number + 1):
    sum_of_numbers += i

# Print the result
print("Sum is:", sum_of_numbers)


Enter a number: 4
Sum is: 10


In [ ]:
user_number = int(input(" Please enter a number: "))

count = 0

while user_number != 0:
    user_number = user_number // 10
    count = count + 1

print(f"The total number of digits in your number is: {count}")






Hello! Please enter a number: 8876
Great! The total number of digits in your number is: 4


In [ ]:
rows = 5

for i in range(rows, 0, -1):
    for j in range(i, 0, -1):
        print(j, end=' ')
    print()


5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


In [ ]:
list1 = [10, 20, 30, 40, 50]

for element in reversed(list1):
    print(element)


50
40
30
20
10


In [ ]:
for i in range(-10,0):
  print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [ ]:
my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

for i in range(1,len(my_list), 2):
  print(my_list[i])

20
40
60
80
100


In [ ]:
import numpy as np


sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# Case 1: Sort array by the second row
print("Printing Original array")
print(sampleArray)

# Get indices that would sort the second row
sorted_indices_row = np.argsort(sampleArray[1, :])

# Use the sorted indices to rearrange the rows
sorted_array_row = sampleArray[:, sorted_indices_row]

print("\nSorting Original array by second row")
print(sorted_array_row)

# Case 2: Sort the array by the second column
# Get indices that would sort the second column
sorted_indices_column = np.argsort(sampleArray[:, 1])

# Use the sorted indices to rearrange the columns
sorted_array_column = sampleArray[sorted_indices_column, :]

print("\nSorting Original array by second column")
print(sorted_array_column)


Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [ ]:
import random
import string

def generate_random_string(length=5):
    # Define the set of characters (uppercase and lowercase letters)
    characters = string.ascii_letters

    # Generate a random string of the specified length
    random_string = ''.join(random.choice(characters) for _ in range(length))

    return random_string

# Example usage
random_string = generate_random_string()
print(random_string)


uspOR


In [ ]:
import random
import string

def generate_random_password():

    # Define the set of characters for each category
    uppercase_letters = string.ascii_uppercase
    lowercase_letters = string.ascii_lowercase
    digits = string.digits
    special_symbols = string.punctuation

    # Ensure at least 2 uppercase letters
    password = random.choices(uppercase_letters, k=2)

    # Add at least 1 digit
    password.extend(random.choice(digits))

    # Add at least 1 special symbol
    password.extend(random.choice(special_symbols))

    # Fill the remaining characters with a combination of lowercase letters, digits, and special symbols
    remaining_length = 10 - len(password)
    password.extend(random.choices(string.ascii_letters + string.digits + string.punctuation, k=remaining_length))

    # Shuffle the password to make it random
    random.shuffle(password)

    # Convert the list of characters to a string
    password = ''.join(password)

    return password

# Example usage
random_password = generate_random_password()
print(random_password)


[1_+^;AkSW
